/**
 * Jade Director - JS Implementation
 * 
 * 调度器：JS 解析 → WASM IR 生成 → WASM 代码生成 → .obj
 */

const { parse } = require('@swc/core');
const path = require('path');
const fs = require('fs');

async function loadNative() {
  const platform = process.platform;
  const arch = process.arch;
  
  const moduleName = platform === 'win32' 
    ? 'jade-native.win32-x64-msvc.node'
    : platform === 'darwin'
      ? arch === 'arm64' 
        ? 'jade-native.darwin-arm64.node'
        : 'jade-native.darwin-x64.node'
      : arch === 'arm64'
        ? 'jade-native.linux-arm64-gnu.node'
        : 'jade-native.linux-x64-gnu.node';
  
  const nativePath = path.join(__dirname, '..', 'native', moduleName);
  
  if (!fs.existsSync(nativePath)) {
    throw new Error(
      `Native module not found: ${moduleName}\n` +
      'Please build it:\n' +
      '  npm run build:native\n' +
      'Or download prebuilt:\n' +
      '  npm run download:native'
    );
  }
  
  return require(nativePath);
}

class Director {
  constructor() {
    this.workdir = process.cwd();
  }

  /**
   * 编译 JS 到原生代码
   */
  async compile(jsCode, options = {}) {
    const {
      outputName = 'app',
      embed = false,
      target = this.detectTarget()
    } = options;

    console.log('=== Jade Director: JS → Native ===\n');
    console.log(`Target: ${target}`);
    console.log(`Mode: ${embed ? 'embed' : 'window'}`);

    const native = await loadNative();
    return await this.compileWithNative(jsCode, native, target, outputName, embed);
  }

  /**
   * Native 编译流程
   */
  async compileWithNative(jsCode, native, target, outputName, embed) {
    const { JadeNative } = native;

    const compiler = new JadeNative();
    compiler.setTarget(target);

    console.log('\n1. Parsing JavaScript...');
    const ast = await this.parseJS(jsCode);
    const astJson = JSON.stringify(ast);
    const nodeCount = this.countNodes(ast);
    console.log(`✅ AST nodes: ${nodeCount}`);

    console.log('\n2. Generating IR (Rust)...');
    const ir = compiler.generateIr(astJson);
    console.log(`✅ Functions: ${ir.functions.length}`);
    console.log(`   Globals: ${ir.globals.length}`);
    console.log(`   Imports: ${ir.imports.length}`);

    // 输出 Rust 源码
    const rustSource = this.generateRustSource(ir, outputName);
    const rustPath = path.join(this.workdir, `${outputName}.rs`);
    fs.writeFileSync(rustPath, rustSource);
    console.log(`\n✅ Rust source: ${rustPath}`);

    console.log('\n3. Generating native code (Cranelift)...');
    const objBytes = compiler.generateCode(JSON.stringify(ir));
    console.log(`✅ Object file: ${objBytes.length} bytes`);

    const outputPath = path.join(this.workdir, `${outputName}.obj`);
    fs.writeFileSync(outputPath, objBytes);
    console.log(`\n✅ Output: ${outputPath}`);

    this.printNextSteps(outputName, embed);
    return outputPath;
  }

  /**
   * 生成 Rust 源码
   */
  generateRustSource(ir, name) {
    const lines = [];
    
    lines.push(`// Auto-generated by @irisverse/jade`);
    lines.push(`// Component: ${name}`);
    lines.push(`// Generated: ${new Date().toISOString()}`);
    lines.push('');
    lines.push('use std::rc::Rc;');
    lines.push('use std::cell::RefCell;');
    lines.push('');
    
    // 导入
    for (const imp of ir.imports) {
      lines.push(`// import: ${imp}`);
    }
    if (ir.imports.length > 0) {
      lines.push('');
    }
    
    // 函数
    for (const funcName of ir.functions) {
      lines.push(`pub fn ${funcName}() {`);
      lines.push(`    // TODO: Implement ${funcName}`);
      lines.push(`    println!("Called ${funcName}");`);
      lines.push(`}`);
      lines.push('');
    }
    
    // 主函数
    lines.push('fn main() {');
    lines.push(`    println!("=== ${name} ===");`);
    
    if (ir.functions.length > 0) {
      lines.push('    ');
      lines.push('    // Call exported functions');
      for (const funcName of ir.functions) {
        lines.push(`    ${funcName}();`);
      }
    }
    
    lines.push('    ');
    lines.push(`    println!("Done.");`);
    lines.push('}');
    
    return lines.join('\n');
  }

  /**
   * 链接为可执行文件
   */
  async link(objPath, libPath, outputPath) {
    const native = await loadNative();
    const { JadeNative } = native;
    const compiler = new JadeNative();
    
    const objBytes = fs.readFileSync(objPath);
    
    console.log('\n=== Linking ===');
    console.log(`Object: ${objPath}`);
    console.log(`Library: ${libPath || '(none)'}`);
    console.log(`Output: ${outputPath}`);
    
    // 设置工作目录为项目根目录（工具链所在位置）
    const originalDir = process.cwd();
    const projectRoot = path.resolve(__dirname, '..', '..', '..');
    process.chdir(projectRoot);
    
    try {
      await compiler.link(objBytes, libPath || '', outputPath);
    } finally {
      process.chdir(originalDir);
    }
    
    console.log(`\n✅ Executable: ${outputPath}`);
    return outputPath;
  }

  /**
   * 打包为静态库
   */
  async packLib(objPath, libName) {
    const native = await loadNative();
    const { JadeNative } = native;
    const compiler = new JadeNative();
    
    const objBytes = fs.readFileSync(objPath);
    
    console.log('\n=== Packing Library ===');
    console.log(`Object: ${objPath}`);
    console.log(`Library: ${libName}`);
    
    // 设置工作目录为项目根目录
    const originalDir = process.cwd();
    const projectRoot = path.resolve(__dirname, '..', '..', '..');
    process.chdir(projectRoot);
    
    try {
      await compiler.linkLib(objBytes, libName, '');
    } finally {
      process.chdir(originalDir);
    }
    
    const outputPath = process.platform === 'win32' 
      ? `${libName}.lib` 
      : `lib${libName}.a`;
    
    console.log(`\n✅ Library: ${outputPath}`);
    return outputPath;
  }

  /**
   * 解析 JS 为 AST
   */
  async parseJS(code) {
    return parse(code, {
      syntax: 'ecmascript',
      target: 'es2020',
      module: true,
      decorators: true,
      dynamicImport: true
    });
  }

  /**
   * 检测目标平台
   */
  detectTarget() {
    const platform = process.platform;
    const arch = process.arch;

    const targetMap = {
      'win32-x64': 'x86_64-pc-windows-msvc',
      'darwin-x64': 'x86_64-apple-darwin',
      'darwin-arm64': 'aarch64-apple-darwin',
      'linux-x64': 'x86_64-unknown-linux-gnu',
      'linux-arm64': 'aarch64-unknown-linux-gnu'
    };

    return targetMap[`${platform}-${arch}`] || 'x86_64-unknown-linux-gnu';
  }

  /**
   * 统计 AST 节点数
   */
  countNodes(node) {
    let count = 0;
    
    const visit = (n) => {
      if (!n || typeof n !== 'object') return;
      count++;
      
      for (const key in n) {
        const value = n[key];
        if (Array.isArray(value)) {
          value.forEach(v => visit(v));
        } else if (value && typeof value === 'object') {
          visit(value);
        }
      }
    };

    visit(node);
    return count;
  }

  /**
   * 打印下一步提示
   */
  printNextSteps(outputName, embed) {
    if (!embed) {
      console.log('\nNext steps:');
      console.log(`  link ${outputName}.obj servo-zero.lib -o ${outputName}.exe`);
    } else {
      console.log('\nNext steps (embed):');
      console.log(`  link ${outputName}.obj -dll -out:${outputName}.dll`);
    }
  }
}

module.exports = { Director, loadNative };
