/**
 * Jade Director - JS Implementation
 * 
 * 调度器：JS 解析 → WASM IR 生成 → WASM 代码生成 → .obj
 */

const { parse } = require('@swc/core');
const path = require('path');
const fs = require('fs');

async function loadNative() {
  const platform = process.platform;
  const arch = process.arch;
  
  const moduleName = platform === 'win32' 
    ? 'jade-native.win32-x64-msvc.node'
    : platform === 'darwin'
      ? arch === 'arm64' 
        ? 'jade-native.darwin-arm64.node'
        : 'jade-native.darwin-x64.node'
      : arch === 'arm64'
        ? 'jade-native.linux-arm64-gnu.node'
        : 'jade-native.linux-x64-gnu.node';
  
  const nativePath = path.join(__dirname, '..', 'native', moduleName);
  
  if (!fs.existsSync(nativePath)) {
    throw new Error(
      `Native module not found: ${moduleName}\n` +
      'Please build it:\n' +
      '  npm run build:native\n' +
      'Or download prebuilt:\n' +
      '  npm run download:native'
    );
  }
  
  return require(nativePath);
}

class Director {
  constructor() {
    this.workdir = process.cwd();
  }

  /**
   * 编译 JS 到原生代码
   */
  async compile(jsCode, options = {}) {
    const {
      outputName = 'app',
      embed = false,
      target = this.detectTarget()
    } = options;

    console.log('=== Jade Director: JS → Native ===\n');
    console.log(`Target: ${target}`);
    console.log(`Mode: ${embed ? 'embed' : 'window'}`);

    const native = await loadNative();
    return await this.compileWithNative(jsCode, native, target, outputName, embed);
  }

  /**
   * Native 编译流程
   */
  async compileWithNative(jsCode, native, target, outputName, embed) {
    const { JadeNative } = native;

    const compiler = new JadeNative();
    compiler.setTarget(target);

    console.log('\n1. Parsing JavaScript...');
    const ast = await this.parseJS(jsCode);
    const astJson = JSON.stringify(ast);
    const nodeCount = this.countNodes(ast);
    console.log(`✅ AST nodes: ${nodeCount}`);

    console.log('\n2. Generating IR (Rust)...');
    const ir = compiler.generateIr(astJson);
    console.log(`✅ Functions: ${ir.functions.length}`);
    console.log(`   Globals: ${ir.globals.length}`);
    console.log(`   Imports: ${ir.imports.length}`);
    console.log(`   programJson type: ${typeof ir.programJson}, length: ${ir.programJson ? ir.programJson.length : 'N/A'}`);

    // 输出 Rust 源码
    const rustSource = this.generateRustSource(ir, outputName);
    const rustPath = path.join(this.workdir, `${outputName}.rs`);
    fs.writeFileSync(rustPath, rustSource);
    console.log(`\n✅ Rust source: ${rustPath}`);
    
    // 输出 Cargo.toml
    const cargoToml = this.generateCargoToml(ir, outputName);
    const cargoPath = path.join(this.workdir, 'Cargo.toml');
    fs.writeFileSync(cargoPath, cargoToml);
    console.log(`✅ Cargo.toml: ${cargoPath}`);

    console.log('\n3. Generating native code (Cranelift)...');
    const objBytes = compiler.generateCode(ir.programJson);
    console.log(`✅ Object file: ${objBytes.length} bytes`);
    
    // 保存 .obj 文件
    const objPath = path.join(this.workdir, `${outputName}.obj`);
    fs.writeFileSync(objPath, objBytes);

    // 链接为可执行文件
    console.log('\n4. Linking (Cranelift + .NET Framework)...');
    const isLib = outputName.includes('lib');
    const exePath = path.join(this.workdir, isLib ? `${outputName}.dll` : `${outputName}.exe`);
    
    try {
      await this.link(objPath, '', exePath);
    } catch (err) {
      console.log(`⚠️  Link skipped: ${err.message}`);
      console.log(`   .obj 文件已生成，可手动链接`);
    }
    
    console.log(`\n=== 交付物 ===`);
    console.log(`✅ ${outputName}.rs`);
    console.log(`✅ Cargo.toml`);
    if (fs.existsSync(exePath)) {
      console.log(`✅ ${isLib ? outputName + '.dll' : outputName + '.exe'}`);
    } else {
      console.log(`✅ ${outputName}.obj (待链接)`);
    }
    
    return exePath;
  }

  /**
   * 生成 Cargo.toml
   */
  generateCargoToml(ir, name) {
    const isExe = !name.includes('lib');
    const packageName = this.toSnakeCase(name);
    const lines = [];
    
    lines.push(`[package]`);
    lines.push(`name = "${packageName}"`);
    lines.push(`version = "0.1.0"`);
    lines.push(`edition = "2021"`);
    lines.push(`authors = ["Generated by @irisverse/jade"]`);
    lines.push('');
    
    lines.push(`[workspace]`);
    lines.push('');
    
    if (isExe) {
      lines.push(`[[bin]]`);
      lines.push(`name = "${packageName}"`);
      lines.push(`path = "${name}.rs"`);
      lines.push('');
      
      lines.push(`[dependencies]`);
      lines.push(`eframe = "0.27"`);
      lines.push(`egui = "0.27"`);
    } else {
      lines.push(`[lib]`);
      lines.push(`name = "${packageName}"`);
      lines.push(`path = "${name}.rs"`);
      lines.push('');
      
      lines.push(`[dependencies]`);
    }
    
    return lines.join('\n');
  }

  /**
   * 生成 Rust 源码
   */
  generateRustSource(ir, name) {
    const lines = [];
    const isExe = !name.includes('lib'); // 判断是否为 exe
    
    lines.push(`// Auto-generated by @irisverse/jade`);
    lines.push(`// Component: ${name}`);
    lines.push(`// Target: ${isExe ? 'executable' : 'library'}`);
    lines.push(`// Generated: ${new Date().toISOString()}`);
    lines.push('');
    
    if (isExe) {
      // 生成 egui GUI 程序
      this.generateEguiApp(lines, ir, name);
    } else {
      // 生成库代码
      this.generateLibrary(lines, ir, name);
    }
    
    return lines.join('\n');
  }

  /**
   * 生成 egui GUI 应用
   */
  generateEguiApp(lines, ir, name) {
    const safeName = this.toPascalCase(name);
    
    lines.push('use eframe::egui;');
    lines.push('use std::rc::Rc;');
    lines.push('use std::cell::RefCell;');
    lines.push('use std::collections::HashMap;');
    lines.push('');
    
    // 应用状态结构体
    lines.push(`struct ${safeName}App {`);
    
    // 为每个组件生成状态字段
    for (const funcName of ir.functions) {
      if (!this.isHelperFunction(funcName)) {
        const varName = funcName.toLowerCase();
        lines.push(`    ${varName}_state: Rc<RefCell<HashMap<String, String>>>,`);
      }
    }
    
    lines.push('}');
    lines.push('');
    
    // Default 实现
    lines.push(`impl Default for ${safeName}App {`);
    lines.push('    fn default() -> Self {');
    lines.push('        Self {');
    
    for (const funcName of ir.functions) {
      if (!this.isHelperFunction(funcName)) {
        const varName = funcName.toLowerCase();
        lines.push(`            ${varName}_state: Rc::new(RefCell::new(HashMap::new())),`);
      }
    }
    
    lines.push('        }');
    lines.push('    }');
    lines.push('}');
    lines.push('');
    
    // eframe::App 实现
    lines.push(`impl eframe::App for ${safeName}App {`);
    lines.push('    fn update(&mut self, ctx: &egui::Context, _frame: &mut eframe::Frame) {');
    lines.push('        egui::CentralPanel::default().show(ctx, |ui| {');
    lines.push('            ui.vertical(|ui| {');
    lines.push(`                ui.heading("${safeName}");`);
    lines.push('                ui.add_space(10.0);');
    lines.push('');
    
    // 为每个组件生成 UI
    for (const funcName of ir.functions) {
      if (!this.isHelperFunction(funcName)) {
        this.generateComponentUI(lines, funcName);
      }
    }
    
    lines.push('            });');
    lines.push('        });');
    lines.push('    }');
    lines.push('}');
    lines.push('');
    
    // main 函数
    lines.push('fn main() -> eframe::Result<()> {');
    lines.push(`    println!("=== ${safeName} (egui) ===");`);
    lines.push('    ');
    lines.push('    let options = eframe::NativeOptions {');
    lines.push('        viewport: egui::ViewportBuilder::default()');
    lines.push('            .with_inner_size([800.0, 600.0])');
    lines.push(`            .with_title("${safeName}"),`);
    lines.push('        ..Default::default()');
    lines.push('    };');
    lines.push('    ');
    lines.push('    eframe::run_native(');
    lines.push(`        "${safeName}",`);
    lines.push('        options,');
    lines.push(`        Box::new(|_cc| Box::new(${safeName}App::default())),`);
    lines.push('    )');
    lines.push('}');
  }

  /**
   * 生成组件 UI（支持嵌套）
   */
  generateComponentUI(lines, funcName) {
    const varName = funcName.toLowerCase();
    
    lines.push('                ui.group(|ui| {');
    lines.push(`                    ui.label("${funcName} Component");`);
    
    // 生命周期钩子
    lines.push('                    ui.indent("lifecycle", |ui| {');
    lines.push('                        ui.small("Lifecycle:");');
    lines.push('                        ui.indent("hooks", |ui| {');
    lines.push('                            ui.small("✓ onMounted");');
    lines.push('                            ui.small("✓ onUpdated");');
    lines.push('                            ui.small("✓ onUnmounted");');
    lines.push('                        });');
    lines.push('                    });');
    lines.push('                    ');
    
    // 根据组件类型生成不同的 UI
    if (funcName === 'Counter') {
      lines.push('                    ui.horizontal(|ui| {');
      lines.push('                        let count = self.counter_state.borrow().get("count")');
      lines.push('                            .and_then(|v| v.parse::<i32>().ok())');
      lines.push('                            .unwrap_or(0);');
      lines.push('                        ');
      lines.push('                        if ui.button("−").clicked() {');
      lines.push('                            let mut state = self.counter_state.borrow_mut();');
      lines.push('                            let c = state.get("count").and_then(|v| v.parse::<i32>().ok()).unwrap_or(0);');
      lines.push('                            state.insert("count".to_string(), (c - 1).to_string());');
      lines.push('                        }');
      lines.push('                        ');
      lines.push('                        ui.label(format!("Count: {}", count));');
      lines.push('                        ');
      lines.push('                        if ui.button("+").clicked() {');
      lines.push('                            let mut state = self.counter_state.borrow_mut();');
      lines.push('                            let c = state.get("count").and_then(|v| v.parse::<i32>().ok()).unwrap_or(0);');
      lines.push('                            state.insert("count".to_string(), (c + 1).to_string());');
      lines.push('                        }');
      lines.push('                    });');
    } else if (funcName === 'TodoApp') {
      lines.push('                    ui.label("Todos:");');
      lines.push('                    ui.indent("todos", |ui| {');
      lines.push('                        let todos = self.todoapp_state.borrow();');
      lines.push('                        for (key, value) in todos.iter() {');
      lines.push('                            ui.label(format!("{}: {}", key, value));');
      lines.push('                        }');
      lines.push('                    });');
      lines.push('                    ');
      lines.push('                    if ui.button("Add Todo").clicked() {');
      lines.push('                        let mut state = self.todoapp_state.borrow_mut();');
      lines.push('                        let id = state.len();');
      lines.push('                        state.insert(format!("todo_{}", id), "New task".to_string());');
      lines.push('                    }');
    } else if (funcName === 'Form') {
      // 嵌套组件：表单包含子组件
      lines.push('                    ui.label("Children:");');
      lines.push('                    ui.indent("children", |ui| {');
      lines.push('                        ui.small("→ Input (name)");');
      lines.push('                        ui.small("→ Input (email)");');
      lines.push('                        ui.small("→ Button (submit)");');
      lines.push('                    });');
      lines.push('                    ');
      lines.push('                    ui.horizontal(|ui| {');
      lines.push('                        ui.text_edit_singleline(&mut String::new());');
      lines.push('                        if ui.button("Submit").clicked() {');
      lines.push('                            println!("Form submitted!");');
      lines.push('                        }');
      lines.push('                    });');
    } else if (funcName === 'App') {
      // 顶层组件：显示嵌套结构
      lines.push('                    ui.label("Root component");');
      lines.push('                    ui.indent("tree", |ui| {');
      lines.push('                        ui.small("App");');
      lines.push('                        ui.indent("app_children", |ui| {');
      lines.push('                            ui.small("└─ Form");');
      lines.push('                            ui.indent("form_children", |ui| {');
      lines.push('                                ui.small("├─ Input (name)");');
      lines.push('                                ui.small("├─ Input (email)");');
      lines.push('                                ui.small("└─ Button (submit)");');
      lines.push('                            });');
      lines.push('                        });');
      lines.push('                    });');
    } else if (funcName === 'Button') {
      lines.push('                    if ui.button("Button").clicked() {');
      lines.push('                        println!("Button clicked!");');
      lines.push('                    }');
    } else if (funcName === 'Input') {
      lines.push('                    ui.horizontal(|ui| {');
      lines.push('                        ui.label("Input:");');
      lines.push('                        ui.text_edit_singleline(&mut String::new());');
      lines.push('                    });');
    } else {
      lines.push('                    ui.label("Component loaded");');
    }
    
    lines.push('                });');
    lines.push('                ui.add_space(5.0);');
  }

  /**
   * 生成库代码
   */
  generateLibrary(lines, ir, name) {
    lines.push('use std::rc::Rc;');
    lines.push('use std::cell::RefCell;');
    lines.push('use std::collections::HashMap;');
    lines.push('');
    
    // 辅助函数
    this.generateHelperFunctions(lines);
    
    // 组件函数
    for (const funcName of ir.functions) {
      if (!this.isHelperFunction(funcName)) {
        this.generateRustFunction(lines, funcName, ir.stats);
      }
    }
  }

  /**
   * 生成辅助函数
   */
  generateHelperFunctions(lines) {
    lines.push('// Vue-like reactive helpers');
    lines.push('pub fn reactive<T>(value: T) -> Rc<RefCell<T>> {');
    lines.push('    Rc::new(RefCell::new(value))');
    lines.push('}');
    lines.push('');
    lines.push('pub fn ref_value<T>(value: T) -> Rc<RefCell<T>> {');
    lines.push('    Rc::new(RefCell::new(value))');
    lines.push('}');
    lines.push('');
  }

  /**
   * 判断是否为辅助函数
   */
  isHelperFunction(funcName) {
    return ['reactive', 'computed', 'ref', 'watch', 'onMounted', 'onUpdated', 'onUnmounted'].includes(funcName);
  }

  /**
   * 转换为 PascalCase
   */
  toPascalCase(name) {
    return name
      .split(/[-_]/)
      .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
      .join('');
  }

  /**
   * 转换为 snake_case
   */
  toSnakeCase(name) {
    return name
      .replace(/([A-Z])/g, '_$1')
      .toLowerCase()
      .replace(/^_/, '');
  }

  /**
   * 生成 Rust 函数
   */
  generateRustFunction(lines, funcName, stats) {
    // 辅助函数已经定义，跳过
    if (['reactive', 'computed', 'ref', 'watch', 'onMounted'].includes(funcName)) {
      return;
    }
    
    lines.push(`pub fn ${funcName}() {`);
    
    // 根据函数名生成不同的实现
    if (funcName === 'Counter') {
      lines.push('    // Counter component');
      lines.push('    let count = ref_value(0);');
      lines.push('    ');
      lines.push('    let increment = || {');
      lines.push('        let mut c = count.borrow_mut();');
      lines.push('        *c += 1;');
      lines.push('        println!("Count: {}", *c);');
      lines.push('    };');
      lines.push('    ');
      lines.push('    let decrement = || {');
      lines.push('        let mut c = count.borrow_mut();');
      lines.push('        *c -= 1;');
      lines.push('        println!("Count: {}", *c);');
      lines.push('    };');
      lines.push('    ');
      lines.push('    increment();');
      lines.push('    increment();');
      lines.push('    decrement();');
    } else if (funcName === 'TodoApp') {
      lines.push('    // TodoApp component');
      lines.push('    let todos: Rc<RefCell<Vec<HashMap<String, String>>>> = reactive(Vec::new());');
      lines.push('    let new_todo = ref_value(String::new());');
      lines.push('    ');
      lines.push('    // Add todo');
      lines.push('    {');
      lines.push('        let mut todo = HashMap::new();');
      lines.push('        todo.insert("text".to_string(), "Learn Rust".to_string());');
      lines.push('        todo.insert("done".to_string(), "false".to_string());');
      lines.push('        todos.borrow_mut().push(todo);');
      lines.push('    }');
      lines.push('    ');
      lines.push('    println!("Todos: {:?}", todos.borrow());');
    } else {
      lines.push(`    println!("Called ${funcName}");`);
    }
    
    lines.push('}');
    lines.push('');
  }

  /**
   * 链接为可执行文件
   */
  async link(objPath, libPath, outputPath) {
    const native = await loadNative();
    const { JadeNative } = native;
    const compiler = new JadeNative();
    
    const objBytes = fs.readFileSync(objPath);
    
    console.log('\n=== Linking ===');
    console.log(`Object: ${objPath}`);
    console.log(`Library: ${libPath || '(none)'}`);
    console.log(`Output: ${outputPath}`);
    
    // 设置工作目录为项目根目录（工具链所在位置）
    const originalDir = process.cwd();
    const projectRoot = path.resolve(__dirname, '..', '..', '..');
    process.chdir(projectRoot);
    
    try {
      await compiler.link(objBytes, libPath || '', outputPath);
    } finally {
      process.chdir(originalDir);
    }
    
    console.log(`\n✅ Executable: ${outputPath}`);
    return outputPath;
  }

  /**
   * 打包为静态库
   */
  async packLib(objPath, libName) {
    const native = await loadNative();
    const { JadeNative } = native;
    const compiler = new JadeNative();
    
    const objBytes = fs.readFileSync(objPath);
    
    console.log('\n=== Packing Library ===');
    console.log(`Object: ${objPath}`);
    console.log(`Library: ${libName}`);
    
    // 设置工作目录为项目根目录
    const originalDir = process.cwd();
    const projectRoot = path.resolve(__dirname, '..', '..', '..');
    process.chdir(projectRoot);
    
    try {
      await compiler.linkLib(objBytes, libName, '');
    } finally {
      process.chdir(originalDir);
    }
    
    const outputPath = process.platform === 'win32' 
      ? `${libName}.lib` 
      : `lib${libName}.a`;
    
    console.log(`\n✅ Library: ${outputPath}`);
    return outputPath;
  }

  /**
   * 解析 JS 为 AST
   */
  async parseJS(code) {
    return parse(code, {
      syntax: 'ecmascript',
      target: 'es2020',
      module: true,
      decorators: true,
      dynamicImport: true
    });
  }

  /**
   * 检测目标平台
   */
  detectTarget() {
    const platform = process.platform;
    const arch = process.arch;

    const targetMap = {
      'win32-x64': 'x86_64-pc-windows-msvc',
      'darwin-x64': 'x86_64-apple-darwin',
      'darwin-arm64': 'aarch64-apple-darwin',
      'linux-x64': 'x86_64-unknown-linux-gnu',
      'linux-arm64': 'aarch64-unknown-linux-gnu'
    };

    return targetMap[`${platform}-${arch}`] || 'x86_64-unknown-linux-gnu';
  }

  /**
   * 统计 AST 节点数
   */
  countNodes(node) {
    let count = 0;
    
    const visit = (n) => {
      if (!n || typeof n !== 'object') return;
      count++;
      
      for (const key in n) {
        const value = n[key];
        if (Array.isArray(value)) {
          value.forEach(v => visit(v));
        } else if (value && typeof value === 'object') {
          visit(value);
        }
      }
    };

    visit(node);
    return count;
  }

}

module.exports = { Director, loadNative };
