use crate::ast::{
    Expression, LiteralValue, Program, Statement, VariableDeclarationKind,
    COMMENT_DEBUGGER, COMMENT_WITH_DEPRECATED, INDENT, RUST_NONE, RUST_UNIT, RUST_SELF,
    RUST_TRUE, RUST_FALSE, RUST_NAN, RUST_INFINITY, RUST_NEG_INFINITY,
};
use crate::error::Result;
use std::collections::HashMap;

pub struct CodeGen {
    indent: usize,
    break_labels: Vec<String>,
    continue_labels: Vec<String>,
    functions: HashMap<String, bool>,
    used_variables: HashMap<String, bool>,
}

impl CodeGen {
    pub fn new() -> Self {
        Self {
            indent: 0,
            break_labels: Vec::new(),
            continue_labels: Vec::new(),
            functions: HashMap::new(),
            used_variables: HashMap::new(),
        }
    }

    pub fn generate(&mut self, program: &Program) -> Result<String> {
        self.collect_functions(program);
        let mut output = String::with_capacity(program.body.len() * 100);
        output.push_str("// Generated by jrust-translator\n\n");
        
        // 分离函数声明和其他语句
        let mut functions = Vec::new();
        let mut statements = Vec::new();
        
        for stmt in &program.body {
            if matches!(stmt, Statement::FunctionDeclaration { .. } | Statement::ClassDeclaration { .. }) {
                let stmt_code = self.generate_statement(stmt, 0)?;
                if !stmt_code.trim().is_empty() {
                    functions.push(stmt_code);
                }
            } else {
                let stmt_code = self.generate_statement(stmt, 0)?;
                if !stmt_code.trim().is_empty() {
                    statements.push(stmt_code);
                }
            }
        }
        
        // 输出函数声明
        for func in functions {
            output.push_str(&func);
            output.push('\n');
        }
        
        // 如果有非函数语句，包裹在 fn main() 中
        if !statements.is_empty() {
            output.push_str("fn main() {\n");
            for stmt in statements {
                output.push_str("    ");
                output.push_str(&stmt);
                output.push('\n');
            }
            output.push_str("}\n");
        }

        Ok(output)
    }

    fn collect_functions(&mut self, program: &Program) {
        for stmt in &program.body {
            self.collect_statement_functions(stmt);
        }
    }

    fn collect_statement_functions(&mut self, stmt: &Statement) {
        match stmt {
            Statement::FunctionDeclaration { id, body, .. } => {
                self.functions.insert(id.name.clone(), true);
                for s in &body.body {
                    self.collect_statement_functions(s);
                }
            }
            Statement::ClassDeclaration { body, .. } => {
                for elem in &body.body {
                    if let Some(crate::ast::MethodDefinition { value, .. }) = &elem.value {
                        if let crate::ast::FunctionExpression::FunctionExpression { id, params, body, .. } = value.as_ref() {
                            if let Some(name) = id {
                                self.functions.insert(name.name.clone(), true);
                            }
                            for s in &body.body {
                                self.collect_statement_functions(s);
                            }
                        }
                    }
                }
            }
            Statement::ForStatement { body, .. } => self.collect_statement_functions(body),
            Statement::WhileStatement { body, .. } => self.collect_statement_functions(body),
            Statement::DoWhileStatement { body, .. } => self.collect_statement_functions(body),
            Statement::IfStatement { consequent, alternate, .. } => {
                self.collect_statement_functions(consequent);
                if let Some(alt) = alternate {
                    self.collect_statement_functions(alt);
                }
            }
            Statement::BlockStatement { body, .. } => {
                for s in body {
                    self.collect_statement_functions(s);
                }
            }
            _ => {}
        }
    }

    fn generate_statement(&mut self, stmt: &Statement, depth: usize) -> Result<String> {
        if depth > crate::ast::MAX_RECURSION_DEPTH {
            return Err(crate::error::Error::RecursionLimitExceeded {
                max: crate::ast::MAX_RECURSION_DEPTH,
            });
        }

        match stmt {
            Statement::ExpressionStatement { expression, .. } => {
                // 检测 IIFE: || { ... }() 或 (function() { ... })()
                if let Expression::CallExpression { callee, arguments, .. } = expression {
                    let is_iife = matches!(
                        callee.as_ref(),
                        Expression::ArrowFunctionExpression { .. } | 
                        Expression::FunctionExpression { .. }
                    );
                    
                    if is_iife && arguments.is_empty() {
                        let callee_code = self.generate_expression(callee, depth)?;
                        return Ok(format!("{{ let _iife = {}; _iife(); }}", callee_code));
                    }
                }
                
                let expr_code = self.generate_expression(expression, depth)?;
                if expr_code.trim().is_empty() {
                    Ok(String::new())
                } else {
                    Ok(format!("{};", expr_code))
                }
            }
            Statement::VariableDeclaration {
                declarations,
                kind,
                ..
            } => {
                let mut output = String::new();
                let keyword = match kind {
                    VariableDeclarationKind::Var => "let mut",
                    VariableDeclarationKind::Let => "let",
                    VariableDeclarationKind::Const => "let",
                };
                for decl in declarations {
                    let name = self.get_pattern_name(&decl.id);
                    self.used_variables.insert(name.clone(), true);
                    output.push_str(&format!("{} {}", keyword, name));
                    output.push_str(" = ");
                    if let Some(init) = &decl.init {
                        output.push_str(&self.generate_expression(init, depth)?);
                    } else {
                        output.push_str("()");
                    }
                    output.push(';');
                }
                Ok(output)
            }
            Statement::FunctionDeclaration {
                id,
                params,
                body,
                ..
            } => {
                let mut output = String::new();
                output.push_str(&format!("fn {}({}) {{\n", id.name, self.generate_params(params)?));
                self.indent += 1;
                for stmt in &body.body {
                    let stmt_code = self.generate_statement(stmt, depth + 1)?;
                    if !stmt_code.trim().is_empty() {
                        output.push_str(&self.indent_str());
                        output.push_str(&stmt_code);
                        output.push('\n');
                    }
                }
                self.indent -= 1;
                output.push_str(&self.indent_str());
                output.push('}');
                Ok(output)
            }
            Statement::ReturnStatement { argument, .. } => {
                let mut output = String::from("return ");
                if let Some(expr) = argument {
                    output.push_str(&self.generate_expression(expr, depth)?);
                }
                output.push(';');
                Ok(output)
            }
            Statement::BlockStatement { body, .. } => {
                let mut output = String::from("{\n");
                self.indent += 1;
                for stmt in body {
                    let stmt_code = self.generate_statement(stmt, depth + 1)?;
                    if !stmt_code.trim().is_empty() {
                        output.push_str(&self.indent_str());
                        output.push_str(&stmt_code);
                        output.push('\n');
                    }
                }
                self.indent -= 1;
                output.push_str(&self.indent_str());
                output.push('}');
                Ok(output)
            }
            Statement::IfStatement {
                test,
                consequent,
                alternate,
                ..
            } => {
                let mut output = format!("if {} {{\n", self.generate_expression(test, depth)?);
                self.indent += 1;
                self.generate_block_body(&mut output, consequent.as_ref(), depth + 1)?;
                self.indent -= 1;
                output.push_str(&self.indent_str());
                if let Some(alt) = alternate {
                    output.push_str("} else ");
                    if matches!(alt.as_ref(), Statement::IfStatement { .. }) {
                        let else_code = self.generate_statement(alt.as_ref(), depth)?;
                        let else_code = else_code.strip_prefix("else ").unwrap_or(&else_code);
                        output.push_str(else_code);
                        output.push('\n');
                    } else {
                        output.push_str("{\n");
                        self.indent += 1;
                        self.generate_block_body(&mut output, alt.as_ref(), depth + 1)?;
                        self.indent -= 1;
                        output.push_str(&self.indent_str());
                        output.push_str("}\n");
                    }
                } else {
                    output.push_str("}\n");
                }
                Ok(output)
            }
            Statement::ForStatement {
                init,
                test,
                update,
                body,
                ..
            } => {
                let mut output = String::new();
                
                // C 风格 for 循环转换为 while 循环
                
                // 初始化部分
                match init {
                    Some(crate::ast::ForStatementInit::Variable(stmt)) => {
                        if let Statement::VariableDeclaration { declarations, kind, .. } = stmt.as_ref() {
                            let keyword = match kind {
                                VariableDeclarationKind::Var => "let mut",
                                VariableDeclarationKind::Let => "let",
                                VariableDeclarationKind::Const => "let",
                            };
                            let decls: Vec<String> = declarations.iter()
                                .map(|decl| {
                                    let name = self.get_pattern_name(&decl.id);
                                    if let Some(init_expr) = &decl.init {
                                        format!("{} = {}", name, self.generate_expression(init_expr, depth).unwrap_or_default())
                                    } else {
                                        name
                                    }
                                })
                                .collect();
                            output.push_str(&format!("{} {};", keyword, decls.join(", ")));
                        }
                    }
                    Some(crate::ast::ForStatementInit::Expression(expr)) => {
                        output.push_str(&self.generate_expression(expr, depth)?);
                        output.push(';');
                    }
                    None => {}
                }

                // while 循环
                output.push_str(" while ");
                let test_expr = test.as_ref()
                    .map(|e| self.generate_expression(e, depth))
                    .unwrap_or(Ok(String::from("true")))?;
                output.push_str(&test_expr);
                output.push_str(" { ");

                // 循环体
                if matches!(body.as_ref(), Statement::BlockStatement { .. }) {
                    if let Statement::BlockStatement { body: block_body, .. } = body.as_ref() {
                        for stmt in block_body {
                            let stmt_code = self.generate_statement(stmt, depth + 1)?;
                            output.push_str(&stmt_code);
                            if !stmt_code.trim().ends_with(';') && !stmt_code.trim().ends_with('}') {
                                output.push(';');
                            }
                        }
                    }
                } else {
                    let body_code = self.generate_statement(body.as_ref(), depth + 1)?;
                    output.push_str(&body_code);
                }

                // 更新部分
                if let Some(upd) = update.as_ref() {
                    output.push_str(" ");
                    output.push_str(&self.generate_expression(upd, depth)?);
                    output.push(';');
                }

                output.push_str(" }");

                Ok(output)
            }
            Statement::WhileStatement { test, body, .. } => {
                let mut output = String::from("while ");
                output.push_str(&self.generate_expression(test, depth)?);
                output.push(' ');
                output.push_str(&self.generate_statement(body.as_ref(), depth)?);
                Ok(output)
            }
            Statement::DoWhileStatement { body, test, .. } => {
                let mut output = String::from("loop {\n");
                self.indent += 1;
                self.generate_block_body(&mut output, body.as_ref(), depth + 1)?;
                self.indent -= 1;
                output.push_str(&self.indent_str());
                output.push_str("if !(");
                output.push_str(&self.generate_expression(test, depth)?);
                output.push_str(") { break; }\n");
                output.push_str(&self.indent_str());
                output.push('}');
                Ok(output)
            }
            Statement::SwitchStatement { discriminant, cases, .. } => {
                let mut output = String::from("match ");
                output.push_str(&self.generate_expression(discriminant, depth)?);
                output.push_str(" {\n");
                for case in cases {
                    if let Some(test) = &case.test {
                        output.push_str(&format!("    {} => {{\n", self.generate_expression(test, depth)?));
                    } else {
                        output.push_str("    _ => {\n");
                    }
                    self.indent += 1;
                    for stmt in &case.consequent {
                        let stmt_code = self.generate_statement(stmt, depth + 1)?;
                        if !stmt_code.trim().is_empty() {
                            output.push_str(&self.indent_str());
                            output.push_str(&stmt_code);
                            output.push('\n');
                        }
                    }
                    self.indent -= 1;
                    output.push_str("    }\n");
                }
                output.push('}');
                Ok(output)
            }
            Statement::BreakStatement { .. } => Ok(String::from("break;")),
            Statement::ContinueStatement { .. } => Ok(String::from("continue;")),
            Statement::TryStatement { block, handler, finalizer, .. } => {
                let mut output = String::from("let _result = (|| {\n");
                self.indent += 1;
                output.push_str(&self.indent_str());
                output.push_str(&self.generate_statement(block.as_ref(), depth + 1)?);
                output.push_str("\n");
                self.indent -= 1;
                output.push_str("})();\n");

                if let Some(catch_block) = handler {
                    let param_name = self.get_pattern_name(&catch_block.param);
                    output.push_str(&format!("let {} = _result;\n", param_name));
                    output.push_str(&self.generate_statement(catch_block.body.as_ref(), depth)?);
                }

                if let Some(finally_block) = finalizer {
                    output.push_str(&self.generate_statement(finally_block.as_ref(), depth)?);
                }

                Ok(output)
            }
            Statement::ThrowStatement { argument, .. } => {
                Ok(format!("panic!(\"{}\");", self.generate_expression(argument, depth)?))
            }
            Statement::ClassDeclaration { id, super_class: _, body, .. } => {
                let mut output = String::new();
                output.push_str(&format!("struct {} {{\n", id.name));
                if let crate::ast::ClassBody { body: elements, .. } = body.as_ref() {
                    self.indent += 1;
                    for elem in elements {
                        if let Some(key) = &elem.key {
                            output.push_str(&self.indent_str());
                            output.push_str(&format!("pub {}: ();\n", self.generate_expression(key, depth)?));
                        }
                    }
                    self.indent -= 1;
                }
                output.push_str("}\n\n");
                Ok(output)
            }
            Statement::ImportDeclaration { specifiers, source, .. } => {
                let mut output = String::from("// import ");
                let names: Vec<String> = specifiers.iter().map(|s| s.local.name.clone()).collect();
                output.push_str(&names.join(", "));
                output.push_str(&format!(" from \"{}\"", source));
                Ok(output)
            }
            Statement::ExportNamedDeclaration { specifiers, source, .. } => {
                let mut output = String::from("// export ");
                let names: Vec<String> = specifiers.iter().map(|s| s.local.name.clone()).collect();
                output.push_str(&names.join(", "));
                if let Some(src) = source {
                    output.push_str(&format!(" from \"{}\"", src));
                }
                Ok(output)
            }
            Statement::ExportDefaultDeclaration { .. } => Ok(String::from("// export default")),
            Statement::ExportAllDeclaration { source, .. } => {
                Ok(format!("// export * from \"{}\"", source))
            }
            Statement::EmptyStatement { .. } => Ok(String::new()),
            Statement::LabeledStatement { label, body, .. } => {
                let mut output = String::new();
                output.push_str(&format!("// {}:\n", label.name));
                output.push_str(&self.generate_statement(body.as_ref(), depth)?);
                Ok(output)
            }
            Statement::ForInStatement { left, right, body, .. } => {
                let left_code = self.generate_for_statement_left(left)?;
                let right_code = self.generate_expression(right, depth)?;
                let body_code = self.generate_statement(body, depth)?;
                if matches!(body.as_ref(), Statement::BlockStatement { .. }) {
                    Ok(format!("for {} in {} {}", left_code, right_code, body_code))
                } else {
                    Ok(format!("for {} in {} {{ {} }}", left_code, right_code, body_code))
                }
            }
            Statement::ForOfStatement { left, right, body, .. } => {
                let left_code = self.generate_for_statement_left(left)?;
                let right_code = self.generate_expression(right, depth)?;
                let body_code = self.generate_statement(body, depth)?;
                if matches!(body.as_ref(), Statement::BlockStatement { .. }) {
                    Ok(format!("for {} in {} {}", left_code, right_code, body_code))
                } else {
                    Ok(format!("for {} in {} {{ {} }}", left_code, right_code, body_code))
                }
            }
            Statement::DebuggerStatement { .. } => Ok(String::from(COMMENT_DEBUGGER)),
            Statement::WithStatement { object, body, .. } => {
                let obj_code = self.generate_expression(object, depth)?;
                let body_code = self.generate_statement(body, depth)?;
                Ok(format!("{} // {}", COMMENT_WITH_DEPRECATED, body_code))
            }
        }
    }

    fn generate_block_body(&mut self, output: &mut String, stmt: &Statement, depth: usize) -> Result<()> {
        match stmt {
            Statement::BlockStatement { body, .. } => {
                for s in body {
                    let stmt_code = self.generate_statement(s, depth)?;
                    if !stmt_code.trim().is_empty() {
                        output.push_str(&self.indent_str());
                        output.push_str(&stmt_code);
                        output.push('\n');
                    }
                }
            }
            _ => {
                let stmt_code = self.generate_statement(stmt, depth)?;
                if !stmt_code.trim().is_empty() {
                    output.push_str(&self.indent_str());
                    output.push_str(&stmt_code);
                    output.push('\n');
                }
            }
        }
        Ok(())
    }

    fn indent_str(&self) -> String {
        INDENT.repeat(self.indent).to_string()
    }

    fn generate_for_statement_left(&mut self, left: &crate::ast::ForStatementLeft) -> Result<String> {
        match left {
            crate::ast::ForStatementLeft::Variable(stmt) => {
                let mut output = String::new();
                if let Statement::VariableDeclaration { declarations, kind, .. } = stmt.as_ref() {
                    let mut_names: Vec<String> = declarations.iter()
                        .map(|decl| self.get_pattern_name(&decl.id))
                        .collect();
                    output.push_str(&mut_names.join(", "));
                }
                Ok(output)
            }
            crate::ast::ForStatementLeft::Pattern(pattern) => {
                Ok(self.get_pattern_name(pattern))
            }
        }
    }

    fn generate_expression(&mut self, expr: &Expression, depth: usize) -> Result<String> {
        if depth > crate::ast::MAX_RECURSION_DEPTH {
            return Err(crate::error::Error::RecursionLimitExceeded {
                max: crate::ast::MAX_RECURSION_DEPTH,
            });
        }

        match expr {
            Expression::Identifier(id) => {
                let name = &id.name;
                if name == "undefined" {
                    Ok(RUST_UNIT.to_string())
                } else if name == "Infinity" {
                    Ok(RUST_INFINITY.to_string())
                } else if name == "NaN" {
                    Ok(RUST_NAN.to_string())
                } else {
                    Ok(self.sanitize_name(name))
                }
            }
            Expression::Literal { value, raw, .. } => Ok(self.generate_literal(value, raw)),
            Expression::BinaryExpression { operator, left, right, .. } => {
                let left_code = self.generate_expression(left, depth)?;
                let right_code = self.generate_expression(right, depth)?;
                let op = self.binary_op_to_rust(operator);
                if matches!(operator, crate::ast::BinaryOperator::In) {
                    Ok(format!("{}.contains(&{})", right_code, left_code))
                } else if matches!(operator, crate::ast::BinaryOperator::InstanceOf) {
                    Ok(format!("{}.is_instance_of::<{}>()", left_code, right_code))
                } else {
                    Ok(format!("({} {} {})", left_code, op, right_code))
                }
            }
            Expression::LogicalExpression { operator, left, right, .. } => {
                let left_code = self.generate_expression(left, depth)?;
                let right_code = self.generate_expression(right, depth)?;
                let op = match operator {
                    crate::ast::LogicalOperator::And => "&&",
                    crate::ast::LogicalOperator::Or => "||",
                };
                Ok(format!("({} {} {})", left_code, op, right_code))
            }
            Expression::NullishCoalescingExpression { left, right, .. } => {
                let left_code = self.generate_expression(left, depth)?;
                let right_code = self.generate_expression(right, depth)?;
                Ok(format!("({}.unwrap_or_else(|| {}))", left_code, right_code))
            }
            Expression::OptionalMemberExpression { object, property, computed, .. } => {
                let obj_code = self.generate_expression(object, depth)?;
                if *computed {
                    let prop_code = self.generate_expression(property, depth)?;
                    Ok(format!("{}.and_then(|o| o.get({}))", obj_code, prop_code))
                } else {
                    let prop_code = self.generate_expression(property, depth)?;
                    Ok(format!("{}.and_then(|o| o.{}())", obj_code, prop_code))
                }
            }
            Expression::OptionalCallExpression { callee, arguments, .. } => {
                let callee_code = self.generate_expression(callee, depth)?;
                let args: Vec<String> = arguments
                    .iter()
                    .map(|a| self.generate_expression(a, depth))
                    .collect::<Result<Vec<_>>>()?;
                Ok(format!("{}.map(|f| f({}))", callee_code, args.join(", ")))
            }
            Expression::UnaryExpression { operator, argument, prefix, .. } => {
                let arg_code = self.generate_expression(argument, depth)?;
                let op = self.unary_op_to_rust(operator);
                if matches!(operator, crate::ast::UnaryOperator::TypeOf) {
                    Ok(format!("_typeof({})", arg_code))
                } else if matches!(operator, crate::ast::UnaryOperator::Delete) {
                    Ok(format!("_delete({})", arg_code))
                } else if matches!(operator, crate::ast::UnaryOperator::Void) {
                    Ok(String::from(RUST_UNIT))
                } else if matches!(operator, crate::ast::UnaryOperator::Minus) && arg_code == RUST_INFINITY {
                    Ok(String::from(RUST_NEG_INFINITY))
                } else if *prefix {
                    Ok(format!("({}{})", op, arg_code))
                } else {
                    Ok(format!("({}{})", arg_code, op))
                }
            }
            Expression::UpdateExpression { operator, argument, prefix, .. } => {
                let arg_code = self.generate_expression(argument, depth)?;
                let op = if matches!(operator, crate::ast::UpdateOperator::Increment) {
                    "+="
                } else {
                    "-="
                };
                if *prefix {
                    Ok(format!("{} {} 1", arg_code, op))
                } else {
                    Ok(format!("{} {} 1", arg_code, op))
                }
            }
            Expression::AssignmentExpression { operator, left, right, .. } => {
                let left_code = self.generate_expression(left, depth)?;
                let right_code = self.generate_expression(right, depth)?;
                let op = self.assignment_op_to_rust(operator);
                Ok(format!("{} {} {}", left_code, op, right_code))
            }
            Expression::CallExpression { callee, arguments, .. } => {
                let callee_code = self.generate_expression(callee, depth)?;
                let args: Vec<String> = arguments
                    .iter()
                    .map(|a| self.generate_expression(a, depth))
                    .collect::<Result<Vec<_>>>()?;
                Ok(format!("{}({})", callee_code, args.join(", ")))
            }
            Expression::MemberExpression { object, property, computed, .. } => {
                let obj_code = self.generate_expression(object, depth)?;
                if *computed {
                    let prop_code = self.generate_expression(property, depth)?;
                    Ok(format!("{}[{}]", obj_code, prop_code))
                } else {
                    let prop_code = self.generate_expression(property, depth)?;
                    Ok(format!("{}.{}", obj_code, prop_code))
                }
            }
            Expression::ArrayExpression { elements, .. } => {
                let items: Vec<String> = elements
                    .iter()
                    .map(|e| match e {
                        Some(expr) => self.generate_expression(expr, depth),
                        None => Ok(String::new()),
                    })
                    .collect::<Result<Vec<_>>>()?;
                Ok(format!("[{}]", items.join(", ")))
            }
            Expression::ObjectExpression { properties, .. } => {
                let mut pairs = Vec::new();
                for prop in properties {
                    let key = self.generate_expression(&prop.key, depth)?;
                    let value = self.generate_expression(&prop.value, depth)?;
                    pairs.push(format!("{}: {}", key, value));
                }
                Ok(format!("{{ {} }}", pairs.join(", ")))
            }
            Expression::This { .. } => Ok(String::from(RUST_SELF)),
            Expression::NewExpression { callee, arguments, .. } => {
                let callee_code = self.generate_expression(callee, depth)?;
                let args: Vec<String> = arguments
                    .iter()
                    .map(|a| self.generate_expression(a, depth))
                    .collect::<Result<Vec<_>>>()?;
                Ok(format!("{}::new({})", callee_code, args.join(", ")))
            }
            Expression::FunctionExpression { id, params, body, loc: _ } => {
                let mut output = String::from("|");
                let param_names: Vec<String> = params
                    .iter()
                    .map(|p| self.get_pattern_name(p))
                    .collect();
                output.push_str(&param_names.join(", "));
                output.push_str("| {\n");
                self.indent += 1;
                for stmt in &body.body {
                    let stmt_code = self.generate_statement(stmt, depth + 1)?;
                    if !stmt_code.trim().is_empty() {
                        output.push_str(&self.indent_str());
                        output.push_str(&stmt_code);
                        output.push('\n');
                    }
                }
                self.indent -= 1;
                output.push_str(&self.indent_str());
                output.push_str("}");
                if let Some(name) = id {
                    output = format!("let {} = {};", name.name, output);
                }
                Ok(output)
            }
            Expression::ClassExpression { id, super_class: _, body, .. } => {
                let name = id.as_ref().map(|i| i.name.clone()).unwrap_or_else(|| "Class".to_string());
                let mut output = String::new();
                output.push_str(&format!("struct {} {{\n", name));
                if let crate::ast::ClassBody { body: elements, .. } = body.as_ref() {
                    self.indent += 1;
                    for elem in elements {
                        if let Some(key) = &elem.key {
                            output.push_str(&self.indent_str());
                            output.push_str(&format!("pub {}: ();\n", self.generate_expression(key, depth)?));
                        }
                    }
                    self.indent -= 1;
                }
                output.push_str(&self.indent_str());
                output.push('}');
                Ok(output)
            }
            Expression::ConditionalExpression { test, consequent, alternate, .. } => {
                let test_code = self.generate_expression(test, depth)?;
                let cons_code = self.generate_expression(consequent, depth)?;
                let alt_code = self.generate_expression(alternate, depth)?;
                Ok(format!("if {} {{ {} }} else {{ {} }}", test_code, cons_code, alt_code))
            }
            Expression::TemplateLiteral { quasis, expressions, .. } => {
                let mut output = String::from("format!(\"");
                for (i, quasi) in quasis.iter().enumerate() {
                    output.push_str(&quasi.value.raw.replace("{", "{{").replace("}", "}}"));
                    if i < expressions.len() {
                        output.push_str(&format!("{{{}}}", i));
                    }
                }
                output.push_str("\", ");
                for (i, expr) in expressions.iter().enumerate() {
                    if i > 0 {
                        output.push_str(", ");
                    }
                    output.push_str(&self.generate_expression(expr, depth)?);
                }
                output.push(')');
                Ok(output)
            }
            Expression::Super { .. } => Ok(String::from("super")),
            Expression::SpreadElement { argument, .. } => {
                Ok(format!("_spread({})", self.generate_expression(argument, depth)?))
            }
            Expression::AwaitExpression { argument, .. } => {
                Ok(format!("await {}", self.generate_expression(argument, depth)?))
            }
            Expression::YieldExpression { argument, .. } => {
                if let Some(arg) = argument {
                    Ok(format!("yield {}", self.generate_expression(arg, depth)?))
                } else {
                    Ok(String::from("yield"))
                }
            }
            Expression::ArrowFunctionExpression { params, body, .. } => {
                let param_names: Vec<String> = params
                    .iter()
                    .map(|p| self.get_pattern_name(p))
                    .collect();
                match body.as_ref() {
                    crate::ast::ArrowFunctionBody::Expression(expr) => {
                        let expr_code = self.generate_expression(expr, depth)?;
                        // 复杂表达式需要包裹在块中
                        if expr_code.contains("if ") || expr_code.contains("match ") || expr_code.len() > 100 {
                            Ok(format!("|{}| {{ {} }}", param_names.join(", "), expr_code))
                        } else {
                            Ok(format!("|{}| {}", param_names.join(", "), expr_code))
                        }
                    }
                    crate::ast::ArrowFunctionBody::BlockFunctionBody(body) => {
                        let mut output = String::from("|");
                        output.push_str(&param_names.join(", "));
                        output.push_str("| {\n");
                        self.indent += 1;
                        for stmt in &body.body {
                            let stmt_code = self.generate_statement(stmt, depth + 1)?;
                            if !stmt_code.trim().is_empty() {
                                output.push_str(&self.indent_str());
                                output.push_str(&stmt_code);
                                output.push('\n');
                            }
                        }
                        self.indent -= 1;
                        output.push_str(&self.indent_str());
                        output.push_str("}");
                        Ok(output)
                    }
                }
            }
            Expression::Import { .. } => Ok(String::from("import")),
            Expression::TaggedTemplateExpression { tag, quasi, .. } => {
                let tag_code = self.generate_expression(tag, depth)?;
                let quasi_code = self.generate_expression(quasi, depth)?;
                Ok(format!("{}({})", tag_code, quasi_code))
            }
            Expression::SequenceExpression { expressions, .. } => {
                let codes: Vec<String> = expressions
                    .iter()
                    .map(|e| self.generate_expression(e, depth))
                    .collect::<Result<Vec<_>>>()?;
                Ok(codes.join(", "))
            }
        }
    }

    fn generate_literal(&self, value: &LiteralValue, raw: &str) -> String {
        match value {
            LiteralValue::Null => RUST_NONE.to_string(),
            LiteralValue::Undefined => RUST_UNIT.to_string(),
            LiteralValue::Boolean(true) => RUST_TRUE.to_string(),
            LiteralValue::Boolean(false) => RUST_FALSE.to_string(),
            LiteralValue::Number(n) => {
                if n.is_nan() {
                    RUST_NAN.to_string()
                } else if n.is_infinite() {
                    if n.is_sign_positive() {
                        RUST_INFINITY.to_string()
                    } else {
                        RUST_NEG_INFINITY.to_string()
                    }
                } else {
                    raw.to_string()
                }
            }
            LiteralValue::String(s) => format!("\"{}\"", s),
            LiteralValue::RegExp { pattern, flags } => {
                format!("// RegExp: /{}/{}", pattern, flags)
            }
        }
    }

    fn binary_op_to_rust(&self, op: &crate::ast::BinaryOperator) -> String {
        use crate::ast::BinaryOperator;
        match op {
            BinaryOperator::Add => "+".to_string(),
            BinaryOperator::Subtract => "-".to_string(),
            BinaryOperator::Multiply => "*".to_string(),
            BinaryOperator::Divide => "/".to_string(),
            BinaryOperator::Modulo => "%".to_string(),
            BinaryOperator::Equal | BinaryOperator::StrictEqual => "==".to_string(),
            BinaryOperator::NotEqual | BinaryOperator::StrictNotEqual => "!=".to_string(),
            BinaryOperator::LessThan => "<".to_string(),
            BinaryOperator::LessThanEqual => "<=".to_string(),
            BinaryOperator::GreaterThan => ">".to_string(),
            BinaryOperator::GreaterThanEqual => ">=".to_string(),
            BinaryOperator::ShiftLeft => "<<".to_string(),
            BinaryOperator::ShiftRight => ">>".to_string(),
            BinaryOperator::ShiftRightUnsigned => ">>>".to_string(),
            BinaryOperator::BitAnd => "&".to_string(),
            BinaryOperator::BitOr => "|".to_string(),
            BinaryOperator::BitXor => "^".to_string(),
            BinaryOperator::Exponent => ".powf()".to_string(),
            BinaryOperator::In | BinaryOperator::InstanceOf => String::new(),
            BinaryOperator::LogicalAnd => "&&".to_string(),
            BinaryOperator::LogicalOr => "||".to_string(),
            BinaryOperator::NullishCoalescing => "??".to_string(),
        }
    }

    fn unary_op_to_rust(&self, op: &crate::ast::UnaryOperator) -> String {
        use crate::ast::UnaryOperator;
        match op {
            UnaryOperator::Minus => "-".to_string(),
            UnaryOperator::Plus => "+".to_string(),
            UnaryOperator::Not => "!".to_string(),
            UnaryOperator::BitNot => "~".to_string(),
            UnaryOperator::TypeOf => "typeof".to_string(),
            UnaryOperator::Void => "void".to_string(),
            UnaryOperator::Delete => "delete".to_string(),
        }
    }

    fn assignment_op_to_rust(&self, op: &crate::ast::AssignmentOperator) -> String {
        use crate::ast::AssignmentOperator;
        match op {
            AssignmentOperator::Simple => "=".to_string(),
            AssignmentOperator::Plus => "+=".to_string(),
            AssignmentOperator::Minus => "-=".to_string(),
            AssignmentOperator::Multiply => "*=".to_string(),
            AssignmentOperator::Divide => "/=".to_string(),
            AssignmentOperator::Modulo => "%=".to_string(),
            AssignmentOperator::BitAnd => "&=".to_string(),
            AssignmentOperator::BitOr => "|=".to_string(),
            AssignmentOperator::BitXor => "^=".to_string(),
            AssignmentOperator::ShiftLeft => "<<=".to_string(),
            AssignmentOperator::ShiftRight => ">>=".to_string(),
            AssignmentOperator::ShiftRightUnsigned => ">>>=".to_string(),
        }
    }

    fn get_pattern_name(&self, pattern: &crate::ast::Pattern) -> String {
        match pattern {
            crate::ast::Pattern::Identifier { id, .. } => self.sanitize_name(&id.name),
            _ => "_".to_string(),
        }
    }

    fn generate_params(&self, params: &[crate::ast::Pattern]) -> Result<String> {
        let names: Vec<String> = params
            .iter()
            .map(|p| self.get_pattern_name(p))
            .collect();
        Ok(names.join(", "))
    }

    fn sanitize_name(&self, name: &str) -> String {
        let rust_keywords = [
            "as", "async", "await", "break", "const", "continue", "crate", "dyn", "else", "enum",
            "extern", "false", "fn", "for", "if", "impl", "in", "let", "loop", "match", "mod",
            "move", "mut", "pub", "ref", "return", "self", "Self", "static", "struct", "super",
            "trait", "true", "type", "unsafe", "use", "where", "while",
        ];

        let mut sanitized = name.to_string();

        if rust_keywords.contains(&name) {
            sanitized = format!("{}_", sanitized);
        }

        if sanitized.chars().next().map(|c| c.is_numeric()).unwrap_or(false) {
            sanitized = format!("_{}", sanitized);
        }

        sanitized
    }
}

impl Default for CodeGen {
    fn default() -> Self {
        Self::new()
    }
}
