/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface IrResult {
  programJson: string
  functions: Array<string>
  globals: Array<string>
  imports: Array<string>
  stats: IrStats
}
export interface IrStats {
  totalFunctions: number
  totalVariables: number
  totalImports: number
  supportedFeatures: Array<string>
}
export declare class JadeNative {
  constructor()
  setTarget(target: string): void
  generateIr(astJson: string): IrResult
  generateCode(programJson: string): Buffer
  link(objBytes: Buffer, libPath: string, outputPath: string): void
  linkLib(objBytes: Buffer, libName: string, outputPath: string): void
  validateJrust(code: string, fullCheck: boolean): boolean
  compileWithRustc(rustCode: string, target: string): Buffer
  checkWithRustc(rustCode: string): boolean
}
