// Auto-generated by @irisverse/jade
// Component: app
// Target: executable
// Generated: 2026-05-23T10:14:09.075Z

use eframe::egui;
use std::rc::Rc;
use std::cell::RefCell;
use std::collections::HashMap;

struct AppApp {
    checkpasswordstrength_state: Rc<RefCell<HashMap<String, String>>>,
    useuserstore_state: Rc<RefCell<HashMap<String, String>>>,
    loginform_state: Rc<RefCell<HashMap<String, String>>>,
    registerform_state: Rc<RefCell<HashMap<String, String>>>,
}

impl Default for AppApp {
    fn default() -> Self {
        Self {
            checkpasswordstrength_state: Rc::new(RefCell::new(HashMap::new())),
            useuserstore_state: Rc::new(RefCell::new(HashMap::new())),
            loginform_state: Rc::new(RefCell::new(HashMap::new())),
            registerform_state: Rc::new(RefCell::new(HashMap::new())),
        }
    }
}

impl eframe::App for AppApp {
    fn update(&mut self, ctx: &egui::Context, _frame: &mut eframe::Frame) {
        egui::CentralPanel::default().show(ctx, |ui| {
            ui.vertical(|ui| {
                ui.group(|ui| {
                    ui.heading("用户登录");
                    ui.add_space(10.0);
                    
                    ui.horizontal(|ui| {
                        ui.label("用户名:");
                        let mut username = self.loginform_state.borrow().get("username")
                            .cloned().unwrap_or_default();
                        ui.text_edit_singleline(&mut username);
                        self.loginform_state.borrow_mut().insert("username".to_string(), username);
                    });
                    
                    ui.horizontal(|ui| {
                        ui.label("密码:");
                        let mut password = self.loginform_state.borrow().get("password")
                            .cloned().unwrap_or_default();
                        ui.text_edit_singleline(&mut password);
                        self.loginform_state.borrow_mut().insert("password".to_string(), password);
                    });
                    
                    ui.horizontal(|ui| {
                        let mut remember = self.loginform_state.borrow().get("remember")
                            .map(|v| v == "true").unwrap_or(false);
                        ui.checkbox(&mut remember, "记住我");
                        self.loginform_state.borrow_mut().insert("remember".to_string(), remember.to_string());
                    });
                    
                    ui.add_space(10.0);
                    ui.horizontal(|ui| {
                        if ui.button("登录").clicked() {
                            let state = self.loginform_state.borrow();
                            let username = state.get("username").cloned().unwrap_or_default();
                            let password = state.get("password").cloned().unwrap_or_default();
                            
                            if username == "admin" && password == "123456" {
                                println!("登录成功！欢迎 {}", username);
                            } else {
                                println!("用户名或密码错误");
                            }
                        }
                        
                        if ui.button("重置").clicked() {
                            self.loginform_state.borrow_mut().clear();
                        }
                    });
                });
                ui.add_space(15.0);
                ui.group(|ui| {
                    ui.heading("用户注册");
                    ui.add_space(10.0);
                    
                    ui.horizontal(|ui| {
                        ui.label("用户名:");
                        let mut username = self.registerform_state.borrow().get("username")
                            .cloned().unwrap_or_default();
                        ui.text_edit_singleline(&mut username);
                        self.registerform_state.borrow_mut().insert("username".to_string(), username);
                    });
                    
                    ui.horizontal(|ui| {
                        ui.label("邮箱:");
                        let mut email = self.registerform_state.borrow().get("email")
                            .cloned().unwrap_or_default();
                        ui.text_edit_singleline(&mut email);
                        self.registerform_state.borrow_mut().insert("email".to_string(), email);
                    });
                    
                    ui.horizontal(|ui| {
                        ui.label("密码:");
                        let mut password = self.registerform_state.borrow().get("password")
                            .cloned().unwrap_or_default();
                        ui.text_edit_singleline(&mut password);
                        self.registerform_state.borrow_mut().insert("password".to_string(), password);
                    });
                    
                    ui.horizontal(|ui| {
                        ui.label("确认密码:");
                        let mut confirm = self.registerform_state.borrow().get("confirmPassword")
                            .cloned().unwrap_or_default();
                        ui.text_edit_singleline(&mut confirm);
                        self.registerform_state.borrow_mut().insert("confirmPassword".to_string(), confirm);
                    });
                    
                    ui.horizontal(|ui| {
                        let mut agree = self.registerform_state.borrow().get("agree")
                            .map(|v| v == "true").unwrap_or(false);
                        ui.checkbox(&mut agree, "同意用户协议");
                        self.registerform_state.borrow_mut().insert("agree".to_string(), agree.to_string());
                    });
                    
                    ui.add_space(10.0);
                    if ui.button("注册").clicked() {
                        let state = self.registerform_state.borrow();
                        let username = state.get("username").cloned().unwrap_or_default();
                        let password = state.get("password").cloned().unwrap_or_default();
                        let confirm = state.get("confirmPassword").cloned().unwrap_or_default();
                        
                        if username.len() < 3 {
                            println!("用户名至少 3 个字符");
                        } else if password.len() < 6 {
                            println!("密码至少 6 位");
                        } else if password != confirm {
                            println!("两次密码不一致");
                        } else {
                            println!("注册成功！请登录");
                        }
                    }
                });
                ui.add_space(15.0);
            });
        });
    }
}

fn main() -> eframe::Result<()> {
    println!("=== App (egui) ===");
    
    let options = eframe::NativeOptions {
        viewport: egui::ViewportBuilder::default()
            .with_inner_size([800.0, 600.0])
            .with_title("App"),
        ..Default::default()
    };
    
    eframe::run_native(
        "App",
        options,
        Box::new(|cc| {
            // 设置中文字体支持
            let mut fonts = egui::FontDefinitions::default();
            fonts.font_data.insert(
                "my_font".to_owned(),
                egui::FontData::from_static(include_bytes!("C:/Windows/Fonts/msyh.ttc")),
            );
            fonts.families.entry(egui::FontFamily::Proportional).or_default()
                .insert(0, "my_font".to_owned());
            cc.egui_ctx.set_fonts(fonts);
            Box::new(AppApp::default())
        }),
    )
}