// Generated by jrust-translator

let counter = 0;
fn increment() {
    let current = (counter + 1);
    console.log("Counter:", current)
    return current;
}
fn createDiv() {
    let div = document.createElement("div");
    div.id = "test-div"
    div.textContent = "Hello from JRust!"
    document.body.appendChild(div)
    console.log("Div created")
}
let result = increment();
console.log("Result:", result)
