//! End-to-end example demonstrating JRust workflow
//! 
//! This example shows how to integrate jrust-translator with jrust-runtime
//! to build native Rust applications from JavaScript source code.

use jrust_runtime::*;
use jrust_runtime::bom::window::Window;
use jrust_runtime::core::*;

fn main() {
    println!("=== JRust End-to-End Demo ===\n");
    
    // Step 1: Initialize the runtime
    println!("Step 1: Initializing JRust Runtime...");
    let mut window = Window::new();
    println!("✓ Runtime initialized\n");
    
    // Step 2: Simulate translated JavaScript code execution
    println!("Step 2: Executing translated JavaScript code...");
    execute_translated_code(&mut window);
    println!("✓ Code executed\n");
    
    // Step 3: Show DOM state
    println!("Step 3: Showing current DOM state...");
    show_dom_state(&window);
    
    println!("\n=== Demo Complete ===");
}

fn execute_translated_code(window: &mut Window) {
    // This simulates what would be generated by jrust-translator
    // from JavaScript code like:
    //
    // const counter = 0;
    // function increment() {
    //   const current = counter + 1;
    //   console.log('Counter:', current);
    //   return current;
    // }
    // let result = increment();
    // console.log('Result:', result);
    
    // Execute the translated logic using jrust-runtime APIs
    let counter = JsValue::new_number(0.0);
    
    // Increment function
    let current = JsValue::new_number(1.0);
    window.console_log(&[
        JsValue::new_string("Counter:"),
        current.clone(),
    ]);
    
    let result = current;
    window.console_log(&[
        JsValue::new_string("Result:"),
        result.clone(),
    ]);
    
    // Create div
    let document = &mut window.document;
    let mut div = document.create_element("div");
    div.set_id("test-div");
    div.set_text_content("Hello from JRust!");
    document.append_to_body(div);
    window.console_log(&[JsValue::new_string("Div created")]);
}

fn show_dom_state(window: &Window) {
    let document = &window.document;
    let body = document.body();
    
    // Print the DOM structure
    println!("Current DOM:");
    println!("  - Body has {} child nodes", body.child_count());
    
    for (i, element) in body.children.iter().enumerate() {
        println!("  - Element #{}: <{} id='{}'>", 
            i + 1, 
            element.tag_name, 
            element.id.as_deref().unwrap_or(""));
        if !element.text_content.is_empty() {
            println!("    Text: \"{}\"", element.text_content);
        }
    }
}
